### ISSUE TITLE
Không hiển thị trong popup khi cài chung vơi các từ điển khác (CEDICT, JMdict ...)

### ISSUE THREAD

**Issue by michael-nhat** [trungnt2910/KanjiDictVN#1]
![image](https://github.com/trungnt2910/KanjiDictVN/assets/66666570/f2511384-c331-4b7f-8578-295d15eb1c5a)
![image](https://github.com/trungnt2910/KanjiDictVN/assets/66666570/d6c3920f-4ef7-4289-97fc-8d4668e00935)
(test trên firefox, linux)
Các từ điển khác vẫn hiển thị chung với nhau trong popup, nhưng Từ điển Hán Nôm chỉ hiển thị khi chỉ mình nó được enable

**Comment by trungnt2910** [comment]
Từ điển này không phải là từ điển định nghĩa từ, mà chỉ bao gồm từ điển chữ Hán (thế nên nó mới được đặt tên là "KanjiDict" + "VN"). Nếu bạn nhấn vào một trong hai chữ Hán trong từ bạn tra, bạn có thể thấy được âm và định nghĩa Hán Việt.

Ví dụ như: 
![image](https://github.com/trungnt2910/KanjiDictVN/assets/57174311/ddff41db-a7b9-4d03-8083-63cf45f17a88)

Về mặt lý thuyết có thể lấy được các từ ghép trên nguồn từ điển Hán Việt rồi tổng hợp nó thành một từ điển giống JMdict, tuy nhiên:
- Số lượng từ ghép rất lớn. Chữ trong KanjiDict (từ điển gốc bằng tiếng Anh) chỉ có khoảng 10350 chữ, có thể lấy được từ trang từ điển Hán Việt mà không làm trang quá tải/làm địa chỉ IP bị chặn.
- Phương pháp thu thập dữ liệu của KanjiDictVN là thu thập định nghĩa Hán Việt dựa trên chữ Hán. Với từng ký tự một, nghĩa các chữ trong tiếng Nhật và tiếng Việt có thể khá gần nhau. Tuy nhiên, với các từ ghép, dùng từ điển Hán Việt có thể gây khó hiểu ví dụ như:
    + Các từ được người Nhật viết bằng chữ Hán nhưng chỉ lấy âm đọc, không lấy nghĩa (VD: 馬鹿).
    + Các từ người Nhật biết bằng chữ Hán nhưng nghĩa đã bị biến tấu khá nhiều (VD: 勉強, 大丈夫) hoặc mang một sắc thái khác so với từ tương ứng trong tiếng Việt (VD: 依頼 không mang ý xấu nhiều bằng từ tiếng Việt "ỷ lại").

**Comment by michael-nhat** [comment]
Thanks bạn. đó không phải là bug mà là tính năng của Yomichan
